name: bedining
description: A new Flutter project.

publish_to: none


# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
version: 1.0.0+1

environment:
  sdk: 3.4.1

dependencies:
#  flutter_launcher_name: 0.0.1
  flutter:
    sdk: flutter
  provider: 6.1.2
  badges: 3.1.2
  intl: ^0.19.0
  http: 1.1.0
  shared_preferences: ^2.2.3
  cloud_firestore: ^5.0.0
  firebase_database: ^11.0.0
  firebase_core: ^3.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

#flutter_launcher_name:
#  name: "bedining"


flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
    - family: pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Medium.ttf


